reporting:
  framework: "A17"
  period: "2019-2024"
  country: "GR"
  group: "Invertebrates"

paths:
  raw_data_dir: "data/raw"
  interim_data_dir: "data/interim"
  derived_data_dir: "data/derived"
  spatial_data_dir: "data/spatial"
  results_dir: "results"
  maps_dir: "results/maps"

inputs:
  taxonomy_curated: "data/raw/species_taxonomy_curated.tsv"
  gbif_occurrences: "data/raw/gbif_invertebrate_species_occ.tsv"
  e1x_mdpp: "data/raw/Ε1Χ_ΒΔ_ΠΡΩΤΟΓΕΝΩΝ_ΦΔ+ΜΔΠΠ_2014-2024_v8.xlsx"
  e1x_db: "data/raw/Ε1Χ_ΒΔ_ΠΡΩΤΟΓΕΝΩΝ_ΥΠ4_ΑΣΠΟΝΔΥΛΑ_20241204.xlsx"
  e1x_ref: "data/raw/Ε1Χ_ΒΔ_ΒΙΒΛΙΟΓΡΑΦΙΑΣ_ΑΣΠ_20250802.xlsx"
  e2x_db: "data/raw/E2X_DB.tsv"
  e2x_ref_unio_crassus: "data/raw/E2X_ref_unio_crassus_complex_supplementary.xlsx"
  e2x_ref_stenobothrus_eurasius: "data/raw/E2X_ref_stenobothrus_eurasius.tsv"
  private_occurrences: "data/raw/Invertebrates_records_private_20250427.csv"
  necca_redlist_points: "data/raw/necca_redlist/points_invertebrates.gpkg"
  national_report_distribution: "data/raw/National report_2013_2018_shp/GR_Art17_species_distribution.shp"
  national_report_distribution_sensitive: "data/raw/National report_2013_2018_shp/GR_Art17_species_distribution_sensitive.shp"
  p_apollo_action_plan: "data/raw/Parnassius apollo AP 2019/AP_Papollo_Distribution_LAEA.shp"

  greece_regions: "data/spatial/gadm41_GRC_shp/gadm41_GRC_2.shp"
  eea_grid_1km: "data/spatial/eea_reference_grid/gr_1km.shp"
  eea_grid_10km: "data/spatial/eea_reference_grid/gr_10km.shp"
  natura2000: "data/spatial/N2000_spatial_GR_2021_12_09_v32/N2000_spatial_GR_2021_12_09_v32.shp"
  eu_dem: "data/spatial/EU_DEM_mosaic_5deg_gr/crop_eudem_dem_3035_europe.tif"

outputs:
  species_occurrences_invertebrates: "data/derived/species_occurrences_invertebrates.tsv"
  species_samples_art17_all: "data/derived/species_samples_art17_all.tsv"

  species_samples_presence_final: "results/species_samples_presence_final.tsv"
  distributions_presence_final: "results/distributions_presence_final.tsv"
  populations_presence_final: "results/populations_presence_final.tsv"
  maps_dir: "results/maps"
